// <auto-generated />
namespace POS_Sys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_profit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_profit));
        
        string IMigrationMetadata.Id
        {
            get { return "202210151922353_add_profit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
